In [16]:
import numpy as np
import pandas as pd
import pydot
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Activation, BatchNormalization, Dropout
from keras.utils import to_categorical
from keras.utils import plot_model


In [2]:
df = pd.read_csv('data/labeled_train.csv')
labels = df["damage_grade"]
labels = to_categorical(labels)
df.drop(["damage_grade"], axis=1, inplace=True)
print(labels)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [3]:
model = Sequential([
    Dense(64, input_dim=71),
    Activation('tanh'),
    Dense(32, input_dim=64),
    Activation('tanh'),
    BatchNormalization(),
    Dropout(0.4),
    Dense(4),
    Activation('softmax'),
])

In [4]:
X_train, X_test, y_train, y_test = train_test_split(df, labels, test_size=0.2)

In [5]:
print('Train data shape: ', X_train.shape)
print('Train labels shape: ', y_train.shape)

Train data shape:  (208480, 71)
Train labels shape:  (208480, 4)


In [6]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [7]:
model.fit(df, labels, epochs=30, batch_size=100)

Epoch 1/30
260601/260601 [==============================] - 3s 11us/step - loss: 1.0006 - accuracy: 0.5505
Epoch 2/30
260601/260601 [==============================] - 3s 11us/step - loss: 0.9222 - accuracy: 0.5687
Epoch 3/30
260601/260601 [==============================] - 3s 10us/step - loss: 0.9180 - accuracy: 0.5688
Epoch 4/30
260601/260601 [==============================] - 3s 11us/step - loss: 0.9164 - accuracy: 0.5688
Epoch 5/30
260601/260601 [==============================] - 3s 11us/step - loss: 0.9157 - accuracy: 0.5689
Epoch 6/30
260601/260601 [==============================] - 3s 11us/step - loss: 0.9150 - accuracy: 0.5689
Epoch 7/30
260601/260601 [==============================] - 3s 11us/step - loss: 0.9146 - accuracy: 0.5689
Epoch 8/30
260601/260601 [==============================] - 3s 11us/step - loss: 0.9143 - accuracy: 0.5689
Epoch 9/30
260601/260601 [==============================] - 3s 11us/step - loss: 0.9142 - accuracy: 0.5689
Epoch 10/30
260601/260601 [==========

In [17]:
plot_model(model, to_file='model.png')

ImportError: Failed to import `pydot`. Please install `pydot`. For example with `pip install pydot`.