In [51]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Activation, BatchNormalization, Dropout
from keras.utils import to_categorical

In [25]:
df = pd.read_csv('data/labeled_train.csv')
labels = df["damage_grade"]
labels = to_categorical(labels)
df.drop(["damage_grade"], axis=1, inplace=True)
print(labels)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [58]:
model = Sequential([
    Dense(64, input_dim=71),
    Activation('tanh'),
    Dense(32, input_dim=64),
    Activation('tanh'),
    BatchNormalization(),
    Dropout(0.4),
    Dense(4),
    Activation('softmax'),
])

In [59]:
X_train, X_test, y_train, y_test = train_test_split(df, labels, test_size=0.2)

In [60]:
print('Train data shape: ', X_train.shape)
print('Train labels shape: ', y_train.shape)

Train data shape:  (208480, 71)
Train labels shape:  (208480, 4)


In [61]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [62]:
model.fit(df, labels, epochs=30, batch_size=100)

Epoch 1/30
260601/260601 [==============================] - 3s 11us/step - loss: 0.9942 - accuracy: 0.5539
Epoch 2/30
260601/260601 [==============================] - 3s 10us/step - loss: 0.9216 - accuracy: 0.5688
Epoch 3/30
260601/260601 [==============================] - 3s 10us/step - loss: 0.9178 - accuracy: 0.5689
Epoch 4/30
260601/260601 [==============================] - 3s 10us/step - loss: 0.9161 - accuracy: 0.5689
Epoch 5/30
260601/260601 [==============================] - 3s 10us/step - loss: 0.9153 - accuracy: 0.5689
Epoch 6/30
260601/260601 [==============================] - 3s 11us/step - loss: 0.9148 - accuracy: 0.5689
Epoch 7/30
260601/260601 [==============================] - 3s 11us/step - loss: 0.9143 - accuracy: 0.5689
Epoch 8/30
260601/260601 [==============================] - 3s 10us/step - loss: 0.9142 - accuracy: 0.5689
Epoch 9/30
260601/260601 [==============================] - 3s 10us/step - loss: 0.9139 - accuracy: 0.5689
Epoch 10/30
260601/260601 [==========