In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('data/labeled_train.csv')

In [4]:
df.head()

Unnamed: 0  Unnamed: 0.1  building_id  geo_level_1_id  geo_level_2_id  \
0           0         47748            4              30             266   
1           1        212102            8              17             409   
2           2         60133           12              17             716   
3           3         34181           16               4             651   
4           4         25045           17               3            1387   

   geo_level_3_id  count_floors_pre_eq  age  area_percentage  \
0            1224                    1   25                5   
1           12182                    2    0               13   
2            7056                    2    5               12   
3             105                    2   80                5   
4            3909                    5   40                5   

   height_percentage  ...  plan_configuration_m  plan_configuration_n  \
0                  2  ...                     0                     0   
1                  7  ...                     0                     0   
2                  6  ...                     0                     0   
3                  4  ...                     0                     0   
4                 10  ...                     0                     0   

   plan_configuration_o  plan_configuration_q  plan_configuration_s  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   

   plan_configuration_u  legal_ownership_status_a  legal_ownership_status_r  \
0                     0                         0                         0   
1                     0                         0                         0   
2                     0                         0                         0   
3                     0                         0                         0   
4                     0                         0                         0   

   legal_ownership_status_v  legal_ownership_status_w  
0                         1                         0  
1                         1                         0  
2                         1                         0  
3                         1                         0  
4                         1                         0  

[5 rows x 72 columns]

In [5]:
labels = df["damage_grade"]
df.drop(["damage_grade"], axis=1, inplace=True)

In [6]:
df.head()

Unnamed: 0  Unnamed: 0.1  building_id  geo_level_1_id  geo_level_2_id  \
0           0         47748            4              30             266   
1           1        212102            8              17             409   
2           2         60133           12              17             716   
3           3         34181           16               4             651   
4           4         25045           17               3            1387   

   geo_level_3_id  count_floors_pre_eq  age  area_percentage  \
0            1224                    1   25                5   
1           12182                    2    0               13   
2            7056                    2    5               12   
3             105                    2   80                5   
4            3909                    5   40                5   

   height_percentage  ...  plan_configuration_m  plan_configuration_n  \
0                  2  ...                     0                     0   
1                  7  ...                     0                     0   
2                  6  ...                     0                     0   
3                  4  ...                     0                     0   
4                 10  ...                     0                     0   

   plan_configuration_o  plan_configuration_q  plan_configuration_s  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   

   plan_configuration_u  legal_ownership_status_a  legal_ownership_status_r  \
0                     0                         0                         0   
1                     0                         0                         0   
2                     0                         0                         0   
3                     0                         0                         0   
4                     0                         0                         0   

   legal_ownership_status_v  legal_ownership_status_w  
0                         1                         0  
1                         1                         0  
2                         1                         0  
3                         1                         0  
4                         1                         0  

[5 rows x 71 columns]

In [7]:
labels.head()

0    2
1    3
2    3
3    2
4    2
Name: damage_grade, dtype: int64

In [8]:
x_train, x_test, y_train, y_test = train_test_split(df, labels, test_size=.2)

In [9]:
kmeans = KMeans(n_clusters=3)
y_pred = kmeans.fit_predict(df)
kmeans.cluster_centers_

array([[1.31111500e+05, 1.30171376e+05, 5.29071197e+05, 1.39076880e+01,
        7.01333718e+02, 6.27522878e+03, 2.12636296e+00, 2.65519890e+01,
        8.01837692e+00, 5.42164110e+00, 8.85580299e-02, 7.61250231e-01,
        3.37391425e-02, 1.89775457e-02, 6.82752726e-02, 7.52055997e-02,
        2.56514507e-01, 8.63749769e-02, 4.25868601e-02, 1.54084273e-02,
        1.46922935e-02, 9.84094899e-01, 1.11405008e-01, 6.35279985e-02,
        3.39817039e-02, 8.08538163e-03, 8.66290889e-04, 3.92718536e-04,
        9.58695250e-04, 1.84808723e-04, 1.38606542e-04, 8.08538163e-05,
        5.33635188e-03, 5.52116060e-03, 4.04731103e-02, 8.40960543e-01,
        5.43568656e-02, 5.86883201e-02, 1.36793107e-01, 3.22722232e-02,
        8.30934670e-01, 7.02365552e-01, 2.35966088e-01, 6.16683607e-02,
        8.05523471e-01, 1.91739050e-03, 9.41369433e-02, 9.46451673e-02,
        3.77702828e-03, 1.52952319e-01, 6.34864166e-01, 4.55669008e-02,
        1.66616614e-01, 5.07877472e-02, 9.00942524e-03, 7.754227

In [10]:
y_pred.shape
df.shape
df['y'] = y_pred
(y_pred == labels).value_counts()

False    202206
True      58395
Name: damage_grade, dtype: int64

In [11]:
np.unique(y_pred)

array([0, 1, 2])

In [12]:
np.unique(labels)

array([1, 2, 3], dtype=int64)

In [15]:
y_adjusted = [i + 1 for i in y_pred]
np.unique(y_adjusted)

array([1, 2, 3])

In [26]:
(y_adjusted == labels).value_counts()

False    173664
True      86937
Name: damage_grade, dtype: int64

In [42]:
y_adjusted = [i + 1 if i!=3 else i**0 for i in y_adjusted]

In [47]:
type(labels)

pandas.core.series.Series

In [43]:
(y_adjusted == labels).value_counts()

False    173393
True      87208
Name: damage_grade, dtype: int64